app = "seedy-typey-backend"
primary_region = "iad"

[build]
  dockerfile = "server/Dockerfile"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  
  [[http_service.checks]]
    interval = 10000
    grace_period = "5s"
    method = "GET"
    path = "/"
    timeout = 2000